Update vc-http-api.yml
Fix bad indentation causing error displaying yml

```
Error parsing https://w3c-ccg.github.io/vc-http-api/vc-http-api.yml bad indentation of a mapping entry at line 564, column 19: properties: ^
Stack trace
SyntaxError: Error parsing https://w3c-ccg.github.io/vc-http-api/vc-http-api.yml 
bad indentation of a mapping entry at line 564, column 19:
            properties:
                      ^
    at Function.syntax (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:29:28051)
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:49:36743

YAMLException: bad indentation of a mapping entry at line 564, column 19:
            properties:
                      ^
    at S (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:88:7371)
    at T (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:88:7469)
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:88:13938
    at U (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:88:14091)
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:88:13795
    at U (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:88:14091)
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:88:13795
    at U (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:88:14091)
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:88:13795
    at U (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:88:14091)

ReDoc Version: 2.0.0-rc.50
Commit: 8bee3d5
```